// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SensorMonitoring.Data;

#nullable disable

namespace SensorMonitoring.Data.Migrations
{
    [DbContext(typeof(SensorDbContext))]
    [Migration("20260610213643_AddConsensusValueMetadata")]
    partial class AddConsensusValueMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SensorMonitoring.Data.Entities.AlarmEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "Timestamp");

                    b.ToTable("AlarmEvents");
                });

            modelBuilder.Entity("SensorMonitoring.Data.Entities.ConsensusValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("CalculatedValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<int>("SensorCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStart")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("ConsensusValues");
                });

            modelBuilder.Entity("SensorMonitoring.Data.Entities.Sensor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("AlarmThreshold1")
                        .HasColumnType("double precision");

                    b.Property<double>("AlarmThreshold2")
                        .HasColumnType("double precision");

                    b.Property<double>("AlarmThreshold3")
                        .HasColumnType("double precision");

                    b.Property<string>("DataQuality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("IsBlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = "SENSOR-001",
                            AlarmThreshold1 = 30.0,
                            AlarmThreshold2 = 32.0,
                            AlarmThreshold3 = 34.0,
                            DataQuality = "Good",
                            IsActive = true,
                            TemperatureMax = 35.0,
                            TemperatureMin = -10.0
                        },
                        new
                        {
                            Id = "SENSOR-002",
                            AlarmThreshold1 = 35.0,
                            AlarmThreshold2 = 37.0,
                            AlarmThreshold3 = 39.0,
                            DataQuality = "Good",
                            IsActive = true,
                            TemperatureMax = 40.0,
                            TemperatureMin = 0.0
                        },
                        new
                        {
                            Id = "SENSOR-003",
                            AlarmThreshold1 = 38.0,
                            AlarmThreshold2 = 41.0,
                            AlarmThreshold3 = 44.0,
                            DataQuality = "Good",
                            IsActive = true,
                            TemperatureMax = 45.0,
                            TemperatureMin = 5.0
                        },
                        new
                        {
                            Id = "SENSOR-004",
                            AlarmThreshold1 = 25.0,
                            AlarmThreshold2 = 27.0,
                            AlarmThreshold3 = 29.0,
                            DataQuality = "Good",
                            IsActive = true,
                            TemperatureMax = 30.0,
                            TemperatureMin = -5.0
                        },
                        new
                        {
                            Id = "SENSOR-005",
                            AlarmThreshold1 = 42.0,
                            AlarmThreshold2 = 46.0,
                            AlarmThreshold3 = 49.0,
                            DataQuality = "Good",
                            IsActive = true,
                            TemperatureMax = 50.0,
                            TemperatureMin = 10.0
                        },
                        new
                        {
                            Id = "SENSOR-006",
                            AlarmThreshold1 = 20.0,
                            AlarmThreshold2 = 22.0,
                            AlarmThreshold3 = 24.0,
                            DataQuality = "Good",
                            IsActive = false,
                            TemperatureMax = 25.0,
                            TemperatureMin = -15.0
                        },
                        new
                        {
                            Id = "SENSOR-007",
                            AlarmThreshold1 = 48.0,
                            AlarmThreshold2 = 51.0,
                            AlarmThreshold3 = 54.0,
                            DataQuality = "Good",
                            IsActive = false,
                            TemperatureMax = 55.0,
                            TemperatureMin = 15.0
                        });
                });

            modelBuilder.Entity("SensorMonitoring.Data.Entities.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AlarmPriority")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConsensus")
                        .HasColumnType("boolean");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "Timestamp");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("SensorMonitoring.Data.Entities.AlarmEvent", b =>
                {
                    b.HasOne("SensorMonitoring.Data.Entities.Sensor", "Sensor")
                        .WithMany("AlarmEvents")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorMonitoring.Data.Entities.SensorReading", b =>
                {
                    b.HasOne("SensorMonitoring.Data.Entities.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorMonitoring.Data.Entities.Sensor", b =>
                {
                    b.Navigation("AlarmEvents");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
